### GENERAL SETTINGS ###

# Site settings
title: Pelayo Arbués.
description: "Pelayo Arbués. Data scientist passionate about data, photography and economics."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: http://twitter.com/pelayoarbues
  - title: linkedin
    url: http://es.linkedin.com/in/pelayogonzalez
  - title: github
    url: http://github.com/pelayoarbues
  - title: instagram
    url: http://instagram.com/pelayoarbues
  - title: tumblr
    url: http://pelayoarbues.tumblr.com

    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Madrid
    - Spain
email: info@pelayoarbues.com
tel: 


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Pelayo Arbués
    position: Ph.D.
    text:
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
 
    
# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Pelayo Arbués holds a Ph.D. in Economics, is passionate about data science, economics and photography"

# Testimonial content. Shown on Home and About page. 
#testimonial:
 #   message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
  #  author: Marcel Newman
  #  position: WEB DESIGNER - BLACKTIE.CO